### ISSUE TITLE
pixel clock

### ISSUE THREAD

**Issue by Edgar-electro** [arsuhinars/MatrixClock#1]
Пожалуйста помогите мне не открывается веб-интерфейс. Всё время пишет подключение и подключение не удалось чем может быть проблема

**Comment by arsuhinars** [comment]
Уже добавил фикс. Попробуйте исправленную версию

**Comment by Edgar-electro** [comment]
Спасибо вам большое попробую

пт, 7 окт. 2022 г., 15:16 Arseny ***@***.***>:
